### PR TITLE
feature: authorisation (basic)

### PR DESCRIPTION
**Pull request by bhavaygoel**

### CODE REVIEW

**Comment by GetPsyched** [comment]
Refactor the env to use [t3](https://env.t3.gg/docs/nextjs), @bhavaygoel.

**Comment by bhavaygoel** [comment]
added validation to env.

**Comment by GetPsyched** [comment]
Will review soon

**Comment by bhavaygoel** [comment]
Added a dummy profile page which shows Unauthorized if not logged in.
Added a check for NEXTAUTH_SECRET in env.

**Review by GetPsyched — APPROVED** [review]
This looks good enough for now. I think we can merge.

**Review by SaketRaman2002 — APPROVED** [review]

**Pull request merged**
