### PR TITLE
Sample data for local database

### PR DESCRIPTION
**Pull request by aryansri-19**
Couldn't test in pgAdmin4 but sql queries are tested in online SQL editor

### CODE REVIEW

**Review by GetPsyched — CHANGES_REQUESTED** [review]
Can you split the insert queries into multiple files by table name? It's hard to review this way.

So something like:
- `database/sample/faculty.sql`
- `database/sample/courses.sql`
- etc.

**Comment by aryansri-19** [comment]
> Can you split the insert queries into multiple files by table name? It's hard to review this way.
> 
> So something like:
> 
> * `database/sample/faculty.sql`
> * `database/sample/courses.sql`
> * etc.

done

**Comment by SGX21** [comment]
@aryansri-19, there are foreign key issues, please check

**Comment by aryansri-19** [comment]
Please specify what is the issue. I have checked inserting the data in the online database, and it worked fine.

**Comment by SGX21** [comment]
cc : @FaLxy

**Comment by FaLxy** [comment]
ERROR:  insert or update on table "club_members" violates foreign key constraint "fk_club_members_clubs"
isac  | 2024-02-10 17:52:34.003 UTC [51] DETAIL:  Key (club_id)=(1) is not present in table "clubs".
isac  | 2024-02-10 17:52:34.003 UTC [51] STATEMENT:  INSERT INTO college_website.club_members (id, student_id, club_id, extra_groups, comments, updated_by)

@aryansri-19, please fix the error,
also provide the link for the online sql editor

**Comment by aryansri-19** [comment]
I think you are executing files alphabetically, that is why it is giving error, as club_id in club_members table depends on id of clubs table which is not inserted yet. You need to first insert tables that do not have a foreign key constraint.
Link to sql editor: https://sqliteonline.com/

**Comment by FaLxy** [comment]
> I think you are executing files alphabetically, that is why it is giving error, as club_id in club_members table depends on id of clubs table which is not inserted yet. You need to first insert tables that do not have a foreign key constraint. Link to sql editor: https://sqliteonline.com/

**Comment by aryansri-19** [comment]
> > I think you are executing files alphabetically, that is why it is giving error, as club_id in club_members table depends on id of clubs table which is not inserted yet. You need to first insert tables that do not have a foreign key constraint. Link to sql editor: https://sqliteonline.com/
> 
> Can you provide the names of the tables that do not have a foreign key constraint?

auth_roles
departments
forms
research_work
roles
sections
students
persons

auth_roles and roles insert queries are not implemented as they will be managed by @SaketRaman2002 or @GetPsyched

**Comment by FaLxy** [comment]
@SaketRaman2002 there are some redundant tables in the schema (auth_roles & roles). Please fix

**Comment by GetPsyched** [comment]
@aryansri-19, prefix all the files in the order that they need to be executed. So, `0_foo.sql`, `1_bar.sql`. Please make these changes quickly.

**Comment by FaLxy** [comment]
`isac  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/11_courses.sql
isac  | 2024-02-12 15:37:55.828 UTC [55] ERROR:  insert or update on table "courses" violates foreign key constraint "fk_courses_majors"
isac  | 2024-02-12 15:37:55.828 UTC [55] DETAIL:  Key (major_id)=(1) is not present in table "majors".
isac  | 2024-02-12 15:37:55.828 UTC [55] STATEMENT:  INSERT INTO college_website.courses (id, code, title, prerequisites, kind, lecture_credits, tutorial_credits, practical_credits, major_id, semester, objectives, content, outcomes, books, "similar")
isac  |         VALUES
isac  |         (1, '1', 'Introduction to Business Administration', ARRAY[]::varchar[], 'Theory', 3, 1, 0, 1, 1, ARRAY['To introduce the students to the field of business administration'], 'The course will cover the basics of business administration', ARRAY['The students will be able to understand the basics of business administration'], ARRAY['Business Administration by John Doe'], ARRAY[]::varchar[]),
isac  |         (2, '2', 'Introduction to Chemistry', ARRAY[]::varchar[], 'Theory', 3, 1, 0, 2, 1, ARRAY['To introduce the students to the field of chemistry'], 'The course will cover the basics of chemistry', ARRAY['The students will be able to understand the basics of chemistry'], ARRAY['Chemistry by Jane Doe'], ARRAY[]::varchar[]),
isac  |         (3, '3', 'Introduction to Civil Engineering', ARRAY[]::varchar[], 'Theory', 3, 1, 0, 3, 1, ARRAY['To introduce the students to the field of civil engineering'], 'The course will cover the basics of civil engineering', ARRAY['The students will be able to understand the basics of civil engineering'], ARRAY['Civil Engineering by John Doe'], ARRAY[]::varchar[]),
isac  |         (4, '4', 'Introduction to Computer Engineering', ARRAY[]::varchar[], 'Theory', 3, 1, 0, 4, 1, ARRAY['To introduce the students to the field of computer engineering'], 'The course will cover the basics of computer engineering', ARRAY['The students will be able to understand the basics of computer engineering'], ARRAY['Computer Engineering by Jane Doe'], ARRAY[]::varchar[]),
isac  |         (5, '5', 'Introduction to Electrical Engineering', ARRAY[]::varchar[], 'Theory', 3, 1, 0, 5, 1, ARRAY['To introduce the students to the field of electrical engineering'], 'The course will cover the basics of electrical engineering', ARRAY['The students will be able to understand the basics of electrical engineering'], ARRAY['Electrical Engineering by John Doe'], ARRAY[]::varchar[]),
isac  |         (6, '6', 'Introduction to Electronics & Communication Engineering', ARRAY[]::varchar[], 'Theory', 3, 1, 0, 6, 1, ARRAY['To introduce the students to the field of electronics & communication engineering'], 'The course will cover the basics of electronics & communication engineering', ARRAY['The students will be able to understand the basics of electronics & communication engineering'], ARRAY['Electronics & Communication Engineering by Jane Doe'], ARRAY[]::varchar[]),
isac  |         (7, '7', 'Introduction to Humanities & Social Sciences', ARRAY[]::varchar[], 'Theory', 3, 1, 0, 7, 1, ARRAY['To introduce the students to the field of humanities & social sciences'], 'The course will cover the basics of humanities & social sciences', ARRAY['The students will be able to understand the basics of humanities & social sciences'], ARRAY['Humanities & Social Sciences by John Doe'], ARRAY[]::varchar[]),
isac  |         (8, '8', 'Introduction to Mathematics', ARRAY[]::varchar[], 'Theory', 3, 1, 0, 8, 1, ARRAY['To introduce the students to the field of mathematics'], 'The course will cover the basics of mathematics', ARRAY['The students will be able to understand the basics of mathematics'], ARRAY['Mathematics by Jane Doe'], ARRAY[]::varchar[]),
isac  |         (9, '9', 'Introduction to Mechanical Engineering', ARRAY[]::varchar[], 'Theory', 3, 1, 0, 9, 1, ARRAY['To introduce the students to the field of mechanical engineering'], 'The course will cover the basics of mechanical engineering', ARRAY['The students will be able to understand the basics of mechanical engineering'], ARRAY['Mechanical Engineering by John Doe'], ARRAY[]::varchar[]),
isac  |         (10, '10', 'Introduction to Physics', ARRAY[]::varchar[], 'Theory', 3, 1, 0, 10, 1, ARRAY['To introduce the students to the field of physics'], 'The course will cover the basics of physics', ARRAY['The students will be able to understand the basics of physics'], ARRAY['Physics by Jane Doe'], ARRAY[]::varchar[]);
isac  | psql:/docker-entrypoint-initdb.d/11_courses.sql:12: ERROR:  insert or update on table "courses" violates foreign key constraint "fk_courses_majors"
isac  | DETAIL:  Key (major_id)=(1) is not present in table "majors".`

@aryansri-19

**Review by SaketRaman2002 — APPROVED** [review]

**Review by GetPsyched — APPROVED** [review]

**Pull request merged**
